module.exports = {
    VOUCHER_1: {
        id: 1,
        tenantId: 1,
        amount: 10,
        code: 'COCA_COLA_BOTTLE',
        userId: '1234',
        title: 'Mega Voucher',
        company: 'Ascendro',
        description: 'a mega voucher',
        shortTitle: 'text',
        isQRCode: true,
        isSpecialPrize: true,
        bonusPointsCosts: 50,
        expirationDate: '2016-11-28T20:48:52Z',
        miniImageId: 'id1-mini',
        normalImageId: 'id1',
        bigImageId: 'id1-big',
        redemptionURL: 'http://voucher1.com'
    },
    VOUCHER_2: {
        id: 2,
        tenantId: 1,
        amount: 10,
        code: 'PEPSI_COLA_BOTTLE',
        userId: '2345',
        title: 'Super Voucher',
        company: 'Ascendro',
        description: 'a super voucher',
        shortTitle: 'text',
        isQRCode: true,
        isSpecialPrize: true,
        bonusPointsCosts: 50,
        expirationDate: '2016-11-28T20:48:52Z',
        miniImageId: 'id2-mini',
        normalImageId: 'id2',
        bigImageId: 'id2-big',
        redemptionURL: 'http://voucher2.com'
    },
}
