package de.ascendro.f4m.service.friend;

import de.ascendro.f4m.service.json.model.type.MessageType;

public enum FriendManagerMessageTypes implements MessageType {

	CONTACT_IMPORT_FACEBOOK, CONTACT_IMPORT_FACEBOOK_RESPONSE,
	CONTACT_IMPORT_PHONEBOOK, CONTACT_IMPORT_PHONEBOOK_RESPONSE,
	CONTACT_LIST, CONTACT_LIST_RESPONSE,
	CONTACT_INVITE, CONTACT_INVITE_RESPONSE,
	CONTACT_INVITE_NEW, CONTACT_INVITE_NEW_RESPONSE,
	CONTACT_REMOVE_INVITATION, CONTACT_REMOVE_INVITATION_RESPONSE,
	CONTACT_RESEND_INVITATION, CONTACT_RESEND_INVITATION_RESPONSE,
	RESYNC, RESYNC_RESPONSE,
	
	PLAYER_BLOCK, PLAYER_BLOCK_RESPONSE,
	PLAYER_UNBLOCK, PLAYER_UNBLOCK_RESPONSE,
	PLAYER_LIST, PLAYER_LIST_RESPONSE,
	PLAYER_LEADERBOARD_LIST, PLAYER_LEADERBOARD_LIST_RESPONSE,

	BUDDY_ADD, BUDDY_ADD_RESPONSE,
	BUDDY_ADD_FOR_USER, BUDDY_ADD_FOR_USER_RESPONSE,
	BUDDY_REMOVE, BUDDY_REMOVE_RESPONSE,
	BUDDY_LIST, BUDDY_LIST_RESPONSE,
	BUDDY_LEADERBOARD_LIST, BUDDY_LEADERBOARD_LIST_RESPONSE,
	BUDDY_LIST_ALL_IDS, BUDDY_LIST_ALL_IDS_RESPONSE,
	
	GROUP_CREATE, GROUP_CREATE_RESPONSE,
	GROUP_GET, GROUP_GET_RESPONSE,
	GROUP_UPDATE, GROUP_UPDATE_RESPONSE,
	GROUP_DELETE, GROUP_DELETE_RESPONSE,
	GROUP_LEAVE,
	GROUP_LIST, GROUP_LIST_RESPONSE,
	GROUP_LIST_MEMBER_OF, GROUP_LIST_MEMBER_OF_RESPONSE,
	GROUP_ADD_PLAYERS, GROUP_ADD_PLAYERS_RESPONSE,
	GROUP_REMOVE_PLAYERS, GROUP_REMOVE_PLAYERS_RESPONSE,
	GROUP_LIST_PLAYERS, GROUP_LIST_PLAYERS_RESPONSE,
	GROUP_BLOCK, GROUP_BLOCK_RESPONSE,
	GROUP_UNBLOCK, GROUP_UNBLOCK_RESPONSE,
	PLAYER_IS_GROUP_MEMBER, PLAYER_IS_GROUP_MEMBER_RESPONSE,
	
	LEADERBOARD_POSITION, LEADERBOARD_POSITION_RESPONSE,

	DAILY_LOGIN, DAILY_LOGIN_RESPONSE,
	APP_RATED, APP_RATED_RESPONSE,
	APP_SHARED, APP_SHARED_RESPONSE,

	MOVE_CONTACTS, MOVE_CONTACTS_RESPONSE,
	MOVE_BUDDIES, MOVE_BUDDIES_RESPONSE,
	MOVE_GROUPS, MOVE_GROUPS_RESPONSE,
	
	ELASTIC_RESYNC, ELASTIC_RESYNC_RESPONSE,

	LAST_DUEL_INVITATION_LIST, LAST_DUEL_INVITATION_LIST_RESPONSE;
	
	public static final String SERVICE_NAME = "friend";

	@Override
	public String getShortName() {
		return convertEnumNameToMessageShortName(name());
	}

	@Override
	public String getNamespace() {
		return SERVICE_NAME;
	}
}
