package de.ascendro.f4m.service.payment;

import de.ascendro.f4m.service.json.model.type.MessageType;

public enum PaymentMessageTypes implements MessageType {

	INIT_EXTERNAL_PAYMENT, INIT_EXTERNAL_PAYMENT_RESPONSE,
	GET_EXTERNAL_PAYMENT, GET_EXTERNAL_PAYMENT_RESPONSE,
	INIT_IDENTIFICATION, INIT_IDENTIFICATION_RESPONSE,
	INSERT_OR_UPDATE_USER, INSERT_OR_UPDATE_USER_RESPONSE,
	MERGE_USERS, MERGE_USERS_RESPONSE,
	CONVERT_BETWEEN_CURRENCIES, CONVERT_BETWEEN_CURRENCIES_RESPONSE,
	GET_ACCOUNT_BALANCE, GET_ACCOUNT_BALANCE_RESPONSE,
	GET_USER_ACCOUNT_BALANCES, GET_USER_ACCOUNT_BALANCES_RESPONSE,
	GET_ACCOUNT_HISTORY, GET_ACCOUNT_HISTORY_RESPONSE,
	GET_USER_ACCOUNT_HISTORY, GET_USER_ACCOUNT_HISTORY_RESPONSE,
	GET_TRANSACTION, GET_TRANSACTION_RESPONSE,
	TRANSFER_BETWEEN_ACCOUNTS, TRANSFER_BETWEEN_ACCOUNTS_RESPONSE,
	GET_IDENTIFICATION, GET_IDENTIFICATION_RESPONSE,
	LOAD_OR_WITHDRAW_WITHOUT_COVERAGE, LOAD_OR_WITHDRAW_WITHOUT_COVERAGE_RESPONSE,
	TRANSFER_JACKPOT, TRANSFER_JACKPOT_RESPONSE,
	GET_EXCHANGE_RATES, GET_EXCHANGE_RATES_RESPONSE,
	CREATE_JACKPOT, CREATE_JACKPOT_RESPONSE,
	GET_JACKPOT, GET_JACKPOT_RESPONSE,
	CLOSE_JACKPOT, CLOSE_JACKPOT_RESPONSE, MOBILE_PURCHASE, MOBILE_PURCHASE_RESPONSE;

    public static final String SERVICE_NAME = "payment";

    @Override
    public String getShortName() {
        return convertEnumNameToMessageShortName(name());
    }

    @Override
    public String getNamespace() {
        return SERVICE_NAME;
    }

    public static boolean isTransferFundsResponseWithTransactionId(PaymentMessageTypes type) {
		return type == TRANSFER_JACKPOT_RESPONSE 
				|| type == LOAD_OR_WITHDRAW_WITHOUT_COVERAGE_RESPONSE
				|| type == TRANSFER_BETWEEN_ACCOUNTS_RESPONSE;
    }
}
