package de.ascendro.f4m.service.voucher;

import de.ascendro.f4m.service.json.model.type.MessageType;

/**
 * Voucher Service supported messages
 */
public enum VoucherMessageTypes implements MessageType {

	VOUCHER_LIST, VOUCHER_LIST_RESPONSE,
	VOUCHER_GET, VOUCHER_GET_RESPONSE,
	VOUCHER_PURCHASE, VOUCHER_PURCHASE_RESPONSE,

	USER_VOUCHER_ASSIGN, USER_VOUCHER_ASSIGN_RESPONSE,
	USER_VOUCHER_LIST, USER_VOUCHER_LIST_RESPONSE,
	USER_VOUCHER_GET, USER_VOUCHER_GET_RESPONSE,
	USER_VOUCHER_USE, USER_VOUCHER_USE_RESPONSE,
	USER_VOUCHER_RESERVE, USER_VOUCHER_RESERVE_RESPONSE,
	USER_VOUCHER_ASSIGN_FOR_TOMBOLA, USER_VOUCHER_ASSIGN_FOR_TOMBOLA_RESPONSE,
	USER_VOUCHER_RELEASE, USER_VOUCHER_RELEASE_RESPONSE,
	USER_VOUCHER_LIST_BY_VOUCHER, USER_VOUCHER_LIST_BY_VOUCHER_RESPONSE,
	USER_VOUCHER_LIST_BY_USER, USER_VOUCHER_LIST_BY_USER_RESPONSE,

	VOUCHER_LIST_DELETE_EXPIRED_ENTRIES, VOUCHER_LIST_DELETE_EXPIRED_ENTRIES_RESPONSE,
	
	MOVE_VOUCHERS, MOVE_VOUCHERS_RESPONSE;

	public static final String SERVICE_NAME = "voucher";

	@Override
	public String getShortName() {
        return convertEnumNameToMessageShortName(name());
	}

	@Override
	public String getNamespace() {
		return SERVICE_NAME;
	}
}