package de.ascendro.f4m.spark.analytics.model;

import static de.ascendro.f4m.server.analytics.model.ShopInvoiceEvent.ARTICLE_ID;
import static de.ascendro.f4m.server.analytics.model.ShopInvoiceEvent.ARTICLE_NUMBER;
import static de.ascendro.f4m.server.analytics.model.ShopInvoiceEvent.ARTICLE_TITLE;
import static de.ascendro.f4m.server.analytics.model.ShopInvoiceEvent.ORIGNAL_PURCHASE_COST;
import static de.ascendro.f4m.server.analytics.model.ShopInvoiceEvent.PAYMENT_BONUS_AMOUNT;
import static de.ascendro.f4m.server.analytics.model.ShopInvoiceEvent.PAYMENT_CREDIT_AMOUNT;
import static de.ascendro.f4m.server.analytics.model.ShopInvoiceEvent.PAYMENT_MONEY_AMOUNT;

import org.apache.spark.sql.types.DataTypes;
import org.apache.spark.sql.types.StructField;

/**
 * The event is generated by OXID shop system when a new order has been placed.
 *
 */
public class ShopInvoiceMessage extends BaseEventMessage {

	private static final String TABLE_SHOP_INVOICE = "shop_invoice";

	public ShopInvoiceMessage(String format, String path) {
		super(format, path, "de.ascendro.f4m.server.analytics.model.ShopInvoiceEvent", TABLE_SHOP_INVOICE);
	}

	@Override
	protected void initColumns() {
        addSelectColumn(ARTICLE_ID);
        addSelectColumn(ARTICLE_NUMBER);
        addSelectColumn(ARTICLE_TITLE);
        addSelectColumn(ORIGNAL_PURCHASE_COST);
        addSelectColumn(PAYMENT_MONEY_AMOUNT);
        addSelectColumn(PAYMENT_BONUS_AMOUNT);
        addSelectColumn(PAYMENT_CREDIT_AMOUNT);
	}

	@Override
	protected StructField[] getEventFields() {
        return new StructField[]{
                DataTypes.createStructField(ARTICLE_ID, DataTypes.StringType, true),
                DataTypes.createStructField(ARTICLE_NUMBER, DataTypes.StringType, true),
                DataTypes.createStructField(ARTICLE_TITLE, DataTypes.StringType, true),
                DataTypes.createStructField(ORIGNAL_PURCHASE_COST, DataTypes.DoubleType, true),
                DataTypes.createStructField(PAYMENT_MONEY_AMOUNT, DataTypes.DoubleType, true),
                DataTypes.createStructField(PAYMENT_BONUS_AMOUNT, DataTypes.DoubleType, true),
                DataTypes.createStructField(PAYMENT_CREDIT_AMOUNT, DataTypes.DoubleType, true)
        };
	}

}
