apiVersion: apps/v1
kind: Deployment
metadata:
  name: promocode-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promocode
      tier: java-backend
  template:
    metadata:
      labels:
        app: promocode
        tier: java-backend
    spec:
        containers:
        - name: promocode-service
          image: gitlab.dev4m.com:4567/k8s-test-lab/f4m-backend-java/promocode-service:latest
          #workingDir: /storage/java/f4m-backend-default-services/f4m-backend-java/promocode-service/target/libs
          #command: ["/usr/bin/java"]
          #args: ["-Dlog4j.configurationFile=file:///storage/java/f4m-backend-default-services/f4m-backend-java/conf/log4j2.xml", "-Djavax.net.ssl.trustStore=/storage/java/f4m-backend-default-services/f4m-backend-java/conf/keystore.jks", "-Djavax.net.ssl.trustStorePassword=f4mkey -Djavax.net.ssl.keyStore=/storage/java/f4m-backend-default-services/f4m-backend-java/conf/keystore.jks", "-Djavax.net.ssl.keyStorePassword=f4mkey", "-Df4m.conf=/storage/f4m.conf", "-cp", "'promocode-service-0.0.1-SNAPSHOT.jar:lib/*'", "de.ascendro.f4m.service.promocode.PromocodeServiceStartup"]
          #command: ["/bin/sh"]
          #args: ["-c", "while true; do echo hello; sleep 10;done"]
          env:
          - name: RABBITMQ_HOST
            value: rabbitmq-svc
         #ports:
         #- containerPort: 5672
         #  name: amqp
          volumeMounts:
          - name: conf
            mountPath: /storage/f4m.conf
            subPath: f4m.conf
        volumes:
        - name: conf
          configMap:
            name: f4m-conf
        imagePullSecrets:
        - name: registry-promocode-token


