package de.ascendro.f4m.service.profile;

import de.ascendro.f4m.service.json.model.type.MessageType;

/**
 * Profile Service supported messages
 */
public enum ProfileMessageTypes implements MessageType {

	CREATE_PROFILE, CREATE_PROFILE_RESPONSE, 
	UPDATE_PROFILE, UPDATE_PROFILE_RESPONSE, 
	GET_PROFILE, GET_PROFILE_RESPONSE, 
	DELETE_PROFILE, DELETE_PROFILE_RESPONSE, 
	MERGE_PROFILE, MERGE_PROFILE_RESPONSE, 
	FIND_BY_IDENTIFIER, FIND_BY_IDENTIFIER_RESPONSE,
	FIND_LIST_BY_IDENTIFIERS, FIND_LIST_BY_IDENTIFIERS_RESPONSE,
	PROFILE_LIST_BY_IDS, PROFILE_LIST_BY_IDS_RESPONSE,
	GET_APP_CONFIGURATION, GET_APP_CONFIGURATION_RESPONSE,
	GET_PROFILE_BLOB, GET_PROFILE_BLOB_RESPONSE,
	UPDATE_PROFILE_BLOB, UPDATE_PROFILE_BLOB_RESPONSE,
    PROFILE_GET, PROFILE_GET_RESPONSE,
    PROFILE_UPDATE, PROFILE_UPDATE_RESPONSE,
    RESYNC, RESYNC_RESPONSE,
    END_CONSUMER_INVOICE_LIST, END_CONSUMER_INVOICE_LIST_RESPONSE;

	public static final String SERVICE_NAME = "profile";

	@Override
	public String getShortName() {
		return convertEnumNameToMessageShortName(name());
	}

	@Override
	public String getNamespace() {
		return SERVICE_NAME;
	}
}