var errors = {
    ERR_NOT_CONNECTED_TO_EVENT_SERVICE: 'ERR_NOT_CONNECTED_TO_EVENT_SERVICE',
    ERR_INVALID_TOPIC: 'ERR_INVALID_TOPIC',
    ERR_ALREADY_SUBSCRIBED: 'ERR_ALREADY_SUBSCRIBED',
    ERR_SUBSCRIPTION_ID_NOT_FOUND: 'ERR_SUBSCRIPTION_ID_NOT_FOUND',
    ERR_NOTIFICATION_CONTENT_IS_REQUIRED: 'ERR_NOTIFICATION_CONTENT_IS_REQUIRED',
    ERR_NO_EVENT_SERVICE_FOUND: 'ERR_NO_INSTANCE_AVAILABLE'
};
module.exports = errors;