package de.ascendro.f4m.service.usermessage.model;

public enum WebsocketMessageType {
    TEXT,
    INVITATION_NOTIFICATION,
    INVITATION_RESPOND_NOTIFICATION,
    INVITATION_EXPIRATION_NOTIFICATION,
    GAME_STARTING_SOON_NOTIFICATION,
	LIVE_TOURNAMENT_STARTING_SOON_NOTIFICATION,
    GAME_PLAYER_READINESS_NOTIFICATION,
    GAME_END,
    PAYMENT_SUCCESS,
    PAYMENT_FAILURE,
    IDENTIFICATION_SUCCESS,
    IDENTIFICATION_FAILURE,
    PLAYER_ADDED_TO_GROUP
}
