USE test;
CREATE TABLE `profile` (
  `userId` varchar(255) NOT NULL,
  `stat_handicap` int(11) NOT NULL DEFAULT '0',
  `stat_appsInstalled` int(11) NOT NULL DEFAULT '0',
  `stat_friendsInvited` int(11) NOT NULL DEFAULT '0',
  `stat_friendsBlocked` int(11) NOT NULL DEFAULT '0',
  `stat_gamesPlayed` int(11) NOT NULL DEFAULT '0',
  `stat_gamesInvitedFromFriends` int(11) NOT NULL DEFAULT '0',
  `stat_gamesFriendsInvitedToo` int(11) NOT NULL DEFAULT '0',
  `stat_gamesPlayedWithFriends` int(11) NOT NULL DEFAULT '0',
  `stat_gamesPlayedWithPublic` int(11) NOT NULL DEFAULT '0',
  `stat_gamesWon` int(11) NOT NULL DEFAULT '0',
  `stat_gamesLost` int(11) NOT NULL DEFAULT '0',
  `stat_gamesDrawn` int(11) NOT NULL DEFAULT '0',
  `stat_rightAnswers` int(11) NOT NULL DEFAULT '0',
  `stat_wrongAnswers` int(11) NOT NULL DEFAULT '0',
  `stat_averageAnswerSpeed` int(11) NOT NULL DEFAULT '0',
  `stat_skippedQuestions` int(11) NOT NULL DEFAULT '0',
  `stat_adsViewed` int(11) NOT NULL DEFAULT '0',
  `stat_paidWinningComponentsPlayed` int(11) NOT NULL DEFAULT '0',
  `stat_freeWinningComponentsPlayed` int(11) NOT NULL DEFAULT '0',
  `stat_skippedWinningComponents` int(11) NOT NULL DEFAULT '0',
  `stat_voucherWon` int(11) NOT NULL DEFAULT '0',
  `stat_superPrizesWon` int(11) NOT NULL DEFAULT '0',
  `stat_bonusPointsWon` int(11) NOT NULL DEFAULT '0',
  `stat_creditsWon` int(11) NOT NULL DEFAULT '0',
  `stat_moneyPlayed` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_moneyWon` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_totalCreditsPurchased` int(11) NOT NULL DEFAULT '0',
  `stat_totalMoneyCharged` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_questionsCreated` int(11) NOT NULL DEFAULT '0',
  `stat_questionsReviewed` int(11) NOT NULL DEFAULT '0',
  `stat_questionsTranslationsCreated` int(11) NOT NULL DEFAULT '0',
  `stat_questionsTranslationsReviewed` int(11) NOT NULL DEFAULT '0',
  `stat_questionsQuality` int(11) NOT NULL DEFAULT '0',
  `stat_favoriteGame` int(11) NOT NULL DEFAULT '0',
  `stat_issuesReported` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`userId`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;
CREATE TABLE `profile_has_stats` (
  `profileId` varchar(255) NOT NULL,
  `tenantId` varchar(255) NOT NULL,
  `stat_handicap` int(11) NOT NULL DEFAULT '0',
  `stat_appsInstalled` int(11) NOT NULL DEFAULT '0',
  `stat_friendsInvited` int(11) NOT NULL DEFAULT '0',
  `stat_friendsBlocked` int(11) NOT NULL DEFAULT '0',
  `stat_gamesPlayed` int(11) NOT NULL DEFAULT '0',
  `stat_gamesInvitedFromFriends` int(11) NOT NULL DEFAULT '0',
  `stat_gamesFriendsInvitedToo` int(11) NOT NULL DEFAULT '0',
  `stat_gamesPlayedWithFriends` int(11) NOT NULL DEFAULT '0',
  `stat_gamesPlayedWithPublic` int(11) NOT NULL DEFAULT '0',
  `stat_gamesWon` int(11) NOT NULL DEFAULT '0',
  `stat_gamesLost` int(11) NOT NULL DEFAULT '0',
  `stat_gamesDrawn` int(11) NOT NULL DEFAULT '0',
  `stat_rightAnswers` int(11) NOT NULL DEFAULT '0',
  `stat_wrongAnswers` int(11) NOT NULL DEFAULT '0',
  `stat_averageAnswerSpeed` int(11) NOT NULL DEFAULT '0',
  `stat_skippedQuestions` int(11) NOT NULL DEFAULT '0',
  `stat_adsViewed` int(11) NOT NULL DEFAULT '0',
  `stat_paidWinningComponentsPlayed` int(11) NOT NULL DEFAULT '0',
  `stat_freeWinningComponentsPlayed` int(11) NOT NULL DEFAULT '0',
  `stat_skippedWinningComponents` int(11) NOT NULL DEFAULT '0',
  `stat_voucherWon` int(11) NOT NULL DEFAULT '0',
  `stat_superPrizesWon` int(11) NOT NULL DEFAULT '0',
  `stat_bonusPointsWon` int(11) NOT NULL DEFAULT '0',
  `stat_creditsWon` int(11) NOT NULL DEFAULT '0',
  `stat_moneyPlayed` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_moneyWon` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_totalCreditsPurchased` int(11) NOT NULL DEFAULT '0',
  `stat_totalMoneyCharged` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_questionsCreated` int(11) NOT NULL DEFAULT '0',
  `stat_questionsReviewed` int(11) NOT NULL DEFAULT '0',
  `stat_questionsTranslationsCreated` int(11) NOT NULL DEFAULT '0',
  `stat_questionsTranslationsReviewed` int(11) NOT NULL DEFAULT '0',
  `stat_questionsQuality` int(11) NOT NULL DEFAULT '0',
  `stat_favoriteGame` int(11) NOT NULL DEFAULT '0',
  `stat_issuesReported` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`profileId`, `tenantId`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;
CREATE TABLE `game` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stat_players` int(11) NOT NULL DEFAULT '0',
  `stat_gamesPlayed` int(11) NOT NULL DEFAULT '0',
  `stat_adsViewed` int(11) NOT NULL DEFAULT '0',
  `stat_creditsPayed` int(11) NOT NULL DEFAULT '0',
  `stat_moneyPayed` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_bonusPointsPaid` int(11) NOT NULL DEFAULT '0',
  `stat_voucherWon` int(11) NOT NULL DEFAULT '0',
  `stat_bonusPointsWon` int(11) NOT NULL DEFAULT '0',
  `stat_creditsWon` int(11) NOT NULL DEFAULT '0',
  `stat_moneyWon` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_questionsAnswered` int(11) NOT NULL DEFAULT '0',
  `stat_questionsAnsweredRight` int(11) NOT NULL DEFAULT '0',
  `stat_questionsAnsweredWrong` int(11) NOT NULL DEFAULT '0',
  `stat_averageAnswerSpeed` int(11) NOT NULL DEFAULT '0',
  `stat_poolsCount` int(11) NOT NULL DEFAULT '0',
  `stat_adsCount` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MEMORY AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
CREATE TABLE `application` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stat_games` int(11) NOT NULL DEFAULT '0',
  `stat_gamesPlayed` int(11) NOT NULL DEFAULT '0',
  `stat_players` int(11) NOT NULL DEFAULT '0',
  `stat_friendsInvited` int(11) NOT NULL DEFAULT '0',
  `stat_quizGames` int(11) NOT NULL DEFAULT '0',
  `stat_moneyGames` int(11) NOT NULL DEFAULT '0',
  `stat_bettingGames` int(11) NOT NULL DEFAULT '0',
  `stat_downloads` int(11) NOT NULL DEFAULT '0',
  `stat_installations` int(11) NOT NULL DEFAULT '0',
  `stat_deinstallations` int(11) NOT NULL DEFAULT '0',
  `stat_moneyCharged` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_creditsPurchased` int(11) NOT NULL DEFAULT '0',
  `stat_moneyWon` decimal(10,2) NOT NULL DEFAULT '0.00',
  `stat_bonusPointsWon` int(11) NOT NULL DEFAULT '0',
  `stat_creditsWon` int(11) NOT NULL DEFAULT '0',
  `stat_voucherWon` int(11) NOT NULL DEFAULT '0',
  `stat_adsViewed` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MEMORY AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
CREATE TABLE `advertisement` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `advertisementProviderId` int(11) NOT NULL,
  `publishIdx` int(11) DEFAULT NULL,
  `stat_appsUsed` int(11) NOT NULL DEFAULT '0',
  `stat_gamesUsed` int(11) NOT NULL DEFAULT '0',
  `stat_views` int(11) NOT NULL DEFAULT '0',
  `stat_earnedCredits` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `advertisementProviderId` (`advertisementProviderId`)
 ) ENGINE=MEMORY DEFAULT CHARSET=utf8;
CREATE TABLE `voucher` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stat_inventoryCount` int(11) NOT NULL DEFAULT '0',
  `stat_won` int(11) NOT NULL DEFAULT '0',
  `stat_archieved` int(11) NOT NULL DEFAULT '0',
  `stat_specialPrizes` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
  ) ENGINE=MEMORY DEFAULT CHARSET=utf8;
 CREATE TABLE `promocode_campaign` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stat_inventoryCount` int(11) NOT NULL DEFAULT '0',
  `stat_used` int(11) NOT NULL DEFAULT '0',
  `stat_creditsPaid` int(11) NOT NULL DEFAULT '0',
  `stat_bonusPointsPaid` int(11) NOT NULL DEFAULT '0',
  `stat_moneyPaid` decimal(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=MEMORY AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
INSERT INTO `advertisement` (`id`, `advertisementProviderId`, `publishIdx`) VALUES(1, 5, 1);
INSERT INTO `advertisement` (`id`, `advertisementProviderId`, `publishIdx`) VALUES(2, 8, 1);
INSERT INTO `application` (`id`) VALUES(1);
INSERT INTO `game` (`id`) VALUES(1);